### ISSUE TITLE
Update sigproc to use coords

### ISSUE THREAD

**Issue by cboulay** [ezmsg-org/ezmsg-sigproc#42]
https://github.com/ezmsg-org/ezmsg/pull/153 will add a CoordinateAxis type allowing irregular axis metadata, such as channel labels or irregular timestamps.

**Comment by griffinmilsap** [comment]
You madman!  So eager to take these for a spin!

**Comment by cboulay** [comment]
Yeah I've got a few layers of transitive dependencies and something on the top that has a release deadline. I could release that thing without these features, but I don't want to be supporting the old way if I don't have to.
